### ISSUE TITLE
nmp start on Windows

### ISSUE THREAD

**Issue by jswilliam93** [alexsong93/momentum-desktop#1]
```
Unhandled rejection TypeError: Cannot read property 'value' of undefined
    at localStorage.allAsync.then.res (C:\Users\jswil\Documents\momentum-desktop\app.js:36:34)
    at tryCatcher (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\relea
mise.js:512:31)
    at Promise._settlePromise (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\promise.
:18)
    at Promise._settlePromise0 (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\promise
4:10)
    at Promise._settlePromises (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\promise
3:18)
    at Promise._fulfill (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\promise.js:638
    at Statement.<anonymous> (C:\Users\jswil\Documents\momentum-desktop\node_modules\bluebird\js\release\nodeback.
21)
    at Statement.replacement (C:\Users\jswil\Documents\momentum-desktop\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.replacement (C:\Users\jswil\Documents\momentum-desktop\node_modules\sqlite3\lib\trace.js:19:31)
```

**Comment by kkumlien** [comment]
Try this approach which does not require npm: https://gist.github.com/kkumlien/d73382148bede541c862239799636360
